-- Drop and recreate Users table (Example)
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS polls CASCADE;
DROP TABLE IF EXISTS options CASCADE;
DROP TABLE IF EXISTS results CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE polls (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  creator_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  shared_link VARCHAR(255) NOT NULL,
  results_link VARCHAR(255) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE options (
  id SERIAL PRIMARY KEY NOT NULL,
  option VARCHAR(255) NOT NULL,
  option_info TEXT NOT NULL,
  poll_id INTEGER REFERENCES polls(id) ON DELETE CASCADE
);

CREATE TABLE results (
  id SERIAL PRIMARY KEY NOT NULL,
  voter_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  option_id INTEGER REFERENCES options(id) ON DELETE CASCADE,
  point INTEGER,
  poll_id INTEGER REFERENCES polls(id) ON DELETE CASCADE
);

